[package]
authors = ["Yuekai Jia <equation618@gmail.com>", "ChengXiang Qi <kuangjux@outlook.com>"]
description = "ArceOS network module"
documentation = "https://arceos-org.github.io/arceos/axnet/index.html"
edition.workspace = true
homepage.workspace = true
license.workspace = true
name = "axnet"
repository = "https://github.com/arceos-org/arceos/tree/main/modules/axnet"
version.workspace = true

[features]
default = ["smoltcp"]
smoltcp = []

[dependencies]
axdriver = {workspace = true, features = ["net"]}
axdriver_net = {git = "https://github.com/arceos-org/axdriver_crates.git", tag = "v0.1.2"}
axerrno = "0.1"
axhal = {workspace = true}
axio = "0.1"
axsync = {workspace = true}
axtask = {workspace = true}
cfg-if = "1.0"
lazyinit = "0.2"
log = "0.4"
spin = "0.10"

[dependencies.smoltcp]
default-features = false
features = [
  "alloc",
  "log", # no std
  "medium-ethernet",
  "proto-ipv4",
  "proto-ipv6",
  "socket-raw",
  "socket-icmp",
  "socket-udp",
  "socket-tcp",
  "socket-dns", # "fragmentation-buffer-size-65536", "proto-ipv4-fragmentation",  # "reassembly-buffer-size-65536", "reassembly-buffer-count-32",
  # "assembler-max-segment-count-32",
]
git = "https://github.com/rcore-os/smoltcp.git"
rev = "21a2f82"
