[package]
authors = ["Zhour Rui <zrufo747@outlook.com>"]
categories.workspace = true
documentation = "https://arceos-org.github.io/arceos/axdma/index.html"
edition.workspace = true
homepage.workspace = true
keywords.workspace = true
license.workspace = true
name = "axdma"
repository = "https://github.com/arceos-org/arceos/tree/main/modules/axdma"
version.workspace = true

[dependencies]
allocator = {git = "https://github.com/arceos-org/allocator.git", tag = "v0.1.1"}
axalloc = {workspace = true}
axconfig = {workspace = true}
axerrno = "0.1"
axhal = {workspace = true, features = ["paging"]}
axmm = {workspace = true}
kspin = "0.1"
log = "0.4"
memory_addr = "0.4"
