[package]
authors = ["Shiping Yuan <robert_yuan@pku.edu.com>"]
description = "ArceOS graphics module"
documentation = "https://arceos-org.github.io/arceos/axdisplay/index.html"
edition.workspace = true
homepage.workspace = true
license.workspace = true
name = "axdisplay"
repository = "https://github.com/arceos-org/arceos/tree/main/modules/axdisplay"
version.workspace = true

[dependencies]
axdriver = {workspace = true, features = ["display"]}
axdriver_display = {git = "https://github.com/arceos-org/axdriver_crates.git", tag = "v0.1.2"}
axsync = {workspace = true}
lazyinit = "0.2"
log = {workspace = true}
