[package]
authors = ["Yuekai Jia <equation618@gmail.com>"]
description = "Macros for multi-level formatted logging used by ArceOS"
documentation = "https://arceos-org.github.io/arceos/axlog/index.html"
edition.workspace = true
homepage.workspace = true
license.workspace = true
name = "axlog"
repository = "https://github.com/arceos-org/arceos/tree/main/modules/axlog"
version.workspace = true

[features]
default = []
log-level-debug = ["log/max_level_debug"]
log-level-error = ["log/max_level_error"]
log-level-info = ["log/max_level_info"]
log-level-off = ["log/max_level_off"]
log-level-trace = ["log/max_level_trace"]
log-level-warn = ["log/max_level_warn"]
std = ["dep:chrono"]

[dependencies]
cfg-if = "1.0"
chrono = {version = "0.4", optional = true}
crate_interface = "0.1"
kspin = "0.1"
log = "0.4"

[dev-dependencies]
axlog = {workspace = true, features = ["std"]}
