[package]
authors = ["Keyang Hu <keyang.hu@qq.com>"]
description = "ArceOS IPI management module"
documentation = "https://arceos-org.github.io/arceos/axipi/index.html"
edition.workspace = true
homepage.workspace = true
license.workspace = true
name = "axipi"
repository = "https://github.com/arceos-org/arceos/tree/main/modules/axipi"
version.workspace = true

[features]
default = []

[dependencies]
axconfig = {workspace = true}
axhal = {workspace = true, features = ["ipi"]}
kspin = {version = "0.1"}
lazyinit = {version = "0.2"}
log = "0.4"
percpu = {version = "0.2.0"}
