[package]
edition = "2024"
name = "phytium-helloworld"
version = "0.1.0"

[dependencies]
axplat-aarch64-dyn = {git = "https://github.com/arceos-hypervisor/axplat-aarch64-dyn", features = ["irq", "smp"]}

axstd = {workspace=true, features = [
  "alloc",
  "paging",
  "irq",
  "multitask",
  "smp",
  "page-alloc-4g",
]}