[package]
edition = "2024"
name = "phytium-test-usb"
version = "0.1.0"

[dependencies]
arceos-ext = {workspace=true}
axplat-aarch64-dyn = {workspace=true, features = ["irq"]}
axstd = {workspace = true, features = [
  "alloc",
  "paging",
  "irq",
  "page-alloc-4g",
]}

log = "0.4"
spin = "0.10"

arceos-usb = {path = "../../driver/arceos-usb"}